server:
  port: 8888 # default

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marklishman/spring-cloud-config-server-ref
          searchPaths: src/main/resources/config,src/main/resources/config/*

# Use file system rather than git
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: src/main/resources/config,src/main/resources/config/{application}