server:
  port: 8888

spring:
  security:
    user:
      name: config
      password: secret

  cloud:
    config:
      server:
        git:
          uri: https://github.com/marklishman/spring-cloud-config-server-ref
          searchPaths: 'src/main/resources/config'

  profiles:
    active: native